# Generated by Django 5.0.2 on 2024-02-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='sponsored',
        ),
        migrations.RemoveField(
            model_name='company',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='company',
            name='improvements_needed',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sustainability_score',
        ),
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='specialty',
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='companies', to='EcoApp.sector'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='specialty',
            field=models.ManyToManyField(blank=True, related_name='advisors', to='EcoApp.specialty'),
        ),
    ]
