# Generated by Django 5.0.2 on 2024-02-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoApp', '0003_advisor_sponsored_company_ranking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='specialty',
            new_name='specialties',
        ),
    ]
